Vinaybackend
CS196Illinois/FA24-Group31 pull request #45
Opened 2024-10-16 02:15 UTC by VINERAJ

uh I forgot to create pull requests for the past couple days. I added riot api calls in case we need them, and added a method to delete the user

2024-10-16 08:41 UTC, adhi-thirumala requested changes
fix changes in the comments + write unit tests for methods

2024-10-16 08:41 UTC, adhi-thirumala commented on Project/backend/java-server/app/src/main/java/org/server/DBController.java
> +            JOptionPane.showMessageDialog(null, "Deleted User");
why did we import a gui library?????

2024-10-16 08:41 UTC, adhi-thirumala commented on Project/backend/java-server/app/src/main/java/org/server/UserController.java
> +            System.out.println("Deleted user: " + uuid);
should be a return value + status code

2024-10-16 08:41 UTC, adhi-thirumala commented on Project/backend/java-server/app/src/main/java/org/server/UserController.java
> +    public void addUser(@PathVariable String uuid, @PathVariable String firstName, @PathVariable String lastName, @PathVariable String riotID, @PathVariable String discordID, @PathVariable String[] o
these are all path variables, but no place for them in the route

2024-10-17 03:39 UTC, yangr0 commented
@VINERAJ 
1. Never force push, it breaks a lot of previous commits. If git is blocking a commit, it's probably for a good reason. Use "git status" to figure out the problem. 
2. Make sure you are pulling from the master branch every time there is a new commit pushed to the master branch to avoid merge conflicts with "git pull origin master". 
3. Do not create a branch like "Vinaybackend", name it something like "delete-user-route". Branches should be created to complete one specific objective only and then destroyed after it has finished it's objective. Staying on one branch will make it very hard to keep up the master branch. 

I made a tutorial about the entire process of making commits and creating branches to this repository. Check the group 31 channel on Discord for the video.

2024-10-17 08:46 UTC, adhi-thirumala commented
still needs above changes

2024-10-17 21:53 UTC, closed without merging